/*
 *  Copyright (C) 2021 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Auto generated file
 */

#ifndef TI_DRIVERS_CONFIG_H_
#define TI_DRIVERS_CONFIG_H_

#include <stdint.h>
#include <drivers/hw_include/cslr_soc.h>
#include "ti_dpl_config.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Common Functions
 */
void System_init(void);
void System_deinit(void);

/*
 * ADC
 */
#include <drivers/adc.h>
#include <drivers/soc.h>

/* ADC Instance Macros */
#define CONFIG_ADC4_BASE_ADDR (CSL_CONTROLSS_ADC4_U_BASE)
#define CONFIG_ADC4_RESULT_BASE_ADDR (CSL_CONTROLSS_ADC4_RESULT_U_BASE)
#define CONFIG_ADC1_BASE_ADDR (CSL_CONTROLSS_ADC1_U_BASE)
#define CONFIG_ADC1_RESULT_BASE_ADDR (CSL_CONTROLSS_ADC1_RESULT_U_BASE)
#define CONFIG_ADC2_BASE_ADDR (CSL_CONTROLSS_ADC2_U_BASE)
#define CONFIG_ADC2_RESULT_BASE_ADDR (CSL_CONTROLSS_ADC2_RESULT_U_BASE)
#define CONFIG_ADC3_BASE_ADDR (CSL_CONTROLSS_ADC3_U_BASE)
#define CONFIG_ADC3_RESULT_BASE_ADDR (CSL_CONTROLSS_ADC3_RESULT_U_BASE)
#define CONFIG_ADC0_BASE_ADDR (CSL_CONTROLSS_ADC0_U_BASE)
#define CONFIG_ADC0_RESULT_BASE_ADDR (CSL_CONTROLSS_ADC0_RESULT_U_BASE)
#define CONFIG_ADC_NUM_INSTANCES (5U)

#define CONFIG_DAC0_BASE_ADDR (CSL_CONTROLSS_DAC0_U_BASE)

/*
 * EDMA
 */
#include <drivers/edma.h>
#include <drivers/soc.h>

/* EDMA Instance Macros */
#define CONFIG_EDMA0_BASE_ADDR (CSL_TPCC0_U_BASE)
#define CONFIG_EDMA0 (0U)
#define CONFIG_EDMA_NUM_INSTANCES (1U)
/*
 * EPWM
 */
#include <drivers/epwm.h>
#include <drivers/soc.h>

/* EPWM Instance Macros */
#define CONFIG_EPWM7_BASE_ADDR (CSL_CONTROLSS_G0_EPWM7_U_BASE)
#define CONFIG_EPWM0_BASE_ADDR (CSL_CONTROLSS_G0_EPWM0_U_BASE)
#define CONFIG_EPWM1_BASE_ADDR (CSL_CONTROLSS_G0_EPWM1_U_BASE)
#define CONFIG_EPWM2_BASE_ADDR (CSL_CONTROLSS_G0_EPWM2_U_BASE)
#define CONFIG_EPWM_NUM_INSTANCES (4U)

/*
 * EQEP
 */
#include <drivers/eqep.h>
#include <drivers/soc.h>

/* EQEP Instance Macros */
#define CONFIG_EQEP2_BASE_ADDR (CSL_CONTROLSS_EQEP2_U_BASE)
#define CONFIG_EQEP_NUM_INSTANCES (1U)

/*
 * GPIO
 */
#include <drivers/gpio.h>
#include <kernel/dpl/AddrTranslateP.h>

/* GPIO PIN Macros */
#define CONFIG_GPIO_RES_INH_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_RES_INH_PIN (129)
#define CONFIG_GPIO_RES_INH_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_RES_INH_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_RES_OTSD_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_RES_OTSD_PIN (128)
#define CONFIG_GPIO_RES_OTSD_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_RES_OTSD_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_NFLT1_H_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_NFLT1_H_PIN (81)
#define CONFIG_GPIO_NFLT1_H_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_NFLT1_H_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_NFLT1_L_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_NFLT1_L_PIN (77)
#define CONFIG_GPIO_NFLT1_L_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_NFLT1_L_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_NFLT2_H_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_NFLT2_H_PIN (79)
#define CONFIG_GPIO_NFLT2_H_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_NFLT2_H_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_NFLT2_L_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_NFLT2_L_PIN (75)
#define CONFIG_GPIO_NFLT2_L_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_NFLT2_L_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_ASC_EN_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_ASC_EN_PIN (69)
#define CONFIG_GPIO_ASC_EN_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_ASC_EN_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_ASC_H_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_ASC_H_PIN (73)
#define CONFIG_GPIO_ASC_H_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_ASC_H_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_ASC_L_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_ASC_L_PIN (71)
#define CONFIG_GPIO_ASC_L_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_ASC_L_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_VINVC_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_VINVC_PIN (125)
#define CONFIG_GPIO_VINVC_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_VINVC_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_OVP_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_OVP_PIN (107)
#define CONFIG_GPIO_OVP_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_OVP_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_OCP_LATCH_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_OCP_LATCH_PIN (115)
#define CONFIG_GPIO_OCP_LATCH_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_OCP_LATCH_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_OTP_LATCH_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_OTP_LATCH_PIN (111)
#define CONFIG_GPIO_OTP_LATCH_DIR (GPIO_DIRECTION_INPUT)
#define CONFIG_GPIO_OTP_LATCH_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_TEST_TOGGLE_BASE_ADDR (CSL_GPIO0_U_BASE)
#define CONFIG_GPIO_TEST_TOGGLE_PIN (83)
#define CONFIG_GPIO_TEST_TOGGLE_DIR (GPIO_DIRECTION_OUTPUT)
#define CONFIG_GPIO_TEST_TOGGLE_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_NUM_INSTANCES (14U)

/*
 * IPC Notify
 */
#include <drivers/ipc_notify.h>

/*
 * IPC RPMessage
 */
#include <drivers/ipc_rpmsg.h>

/*
 * MCSPI
 */
#include <drivers/mcspi.h>

/* MCSPI Instance Macros */
#define CONFIG_MCSPI_UCC (0U)
#define CONFIG_MCSPI_NUM_INSTANCES (1U)
#define CONFIG_MCSPI_NUM_DMA_INSTANCES (0U)


/*
 * UART
 */
#include <drivers/uart.h>

/* UART Instance Macros */
#define CONFIG_UART_CONSOLE (0U)
#define CONFIG_UART_NUM_INSTANCES (1U)
#define CONFIG_UART_NUM_DMA_INSTANCES (0U)



#define DMA_TRIG_XBAR_EDMA_MODULE_0_INPUT   DMA_TRIG_XBAR_DMA_XBAR_OUT_0


#include <drivers/soc.h>
#include <kernel/dpl/CycleCounterP.h>


#ifdef __cplusplus
}
#endif

#endif /* TI_DRIVERS_CONFIG_H_ */
